'use client';

import Link from 'next/link';
import { notFound } from 'next/navigation';
import { useParams } from 'next/navigation';

// Module-specific terms and conditions
// Each module can have its own terms page at /legal/modules/[moduleKey]/terms

export default function ModuleTermsPage() {
  const params = useParams();
  const moduleKey = params?.moduleKey;
  
  // Module-specific terms content
  const moduleTerms = {
    reviews: {
      title: 'Review Reply AI - Terms of Service',
      moduleName: 'Review Reply AI',
      version: '1.0.0',
      sections: [
        {
          title: '1. Service Description',
          content: (
            <p>
              Review Reply AI is an AI-powered service that generates Google review replies for your business. 
              By activating this module, you gain access to automated review response generation tools.
            </p>
          )
        },
        {
          title: '2. Usage Rights and Restrictions',
          content: (
            <p>
              You may use Review Reply AI to generate replies for reviews of your business. Generated content is 
              provided for your review and should be verified before posting. You are responsible for all content 
              posted using this service.
            </p>
          )
        },
        {
          title: '3. AI-Generated Content Disclaimer',
          content: (
            <>
              <p>
                All replies generated by Review Reply AI are suggestions created by artificial intelligence. 
                You are solely responsible for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Reviewing all generated content before publication</li>
                <li>Ensuring accuracy and appropriateness of replies</li>
                <li>Compliance with platform policies (e.g., Google's review policies)</li>
                <li>Any legal or professional consequences of published replies</li>
              </ul>
            </>
          )
        },
        {
          title: '4. Subscription and Billing',
          content: (
            <p>
              Review Reply AI operates on a monthly subscription basis. Your subscription includes a usage limit 
              for generated replies per billing cycle. Additional usage may result in overage charges or require 
              plan upgrades.
            </p>
          )
        },
        {
          title: '5. Data and Privacy',
          content: (
            <p>
              Review Reply AI processes review content and business information to generate replies. All data 
              is handled in accordance with our Privacy Policy. Review content and generated replies may be 
              stored for service improvement purposes.
            </p>
          )
        },
        {
          title: '6. Termination',
          content: (
            <p>
              You may cancel your Review Reply AI subscription at any time through your billing settings. 
              Cancellation will take effect at the end of your current billing period. Access to the service 
              will continue until the period ends.
            </p>
          )
        },
        {
          title: '7. Limitation of Liability',
          content: (
            <>
              <p>
                Review Reply AI provides AI-generated suggestions. We are not liable for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Inappropriate or inaccurate generated content</li>
                <li>Consequences of published replies</li>
                <li>Platform policy violations resulting from generated content</li>
                <li>Business reputation impacts</li>
              </ul>
            </>
          )
        },
        {
          title: '8. Module-Specific Terms',
          content: (
            <p>
              These terms apply specifically to the Review Reply AI module. By activating this module, you 
              agree to these terms in addition to Tavari AI's general Terms of Service.
            </p>
          )
        }
      ]
    },
    'delivery-dispatch': {
      title: 'Last-Mile Delivery - Terms of Service',
      moduleName: 'Last-Mile Delivery',
      version: '1.0.0',
      sections: [
        {
          title: '1. Service Description',
          content: (
            <>
              <p>
                Last-Mile Delivery is a platform that connects your business with third-party delivery providers.
                We facilitate the scheduling and coordination of pickup and delivery requests. <strong>We do not
                perform deliveries ourselves.</strong> All physical delivery services are provided by independent
                third-party carriers or couriers.
              </p>
            </>
          )
        },
        {
          title: '2. Third-Party Delivery Service',
          content: (
            <>
              <p>
                Delivery service is provided exclusively by third-party providers. By using Last-Mile Delivery you
                acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Tavari (and its affiliates) is not a carrier, courier, or delivery company</li>
                <li>We do not employ drivers or operate delivery vehicles</li>
                <li>We act only as a technology platform to connect you with third-party delivery providers</li>
                <li>The third-party provider is solely responsible for performing the pickup and delivery, including
                    safety, timeliness, handling of goods, and compliance with applicable laws</li>
              </ul>
            </>
          )
        },
        {
          title: '3. Your Responsibilities',
          content: (
            <>
              <p>
                You are responsible for: providing accurate pickup and delivery addresses and contact information;
                ensuring that goods are properly packaged and lawful to transport; and complying with all applicable
                laws. You use the platform and any third-party delivery service at your own risk.
              </p>
            </>
          )
        },
        {
          title: '4. No Warranty as to Third-Party Services',
          content: (
            <p>
              We do not guarantee the quality, safety, timeliness, or legality of any third-party delivery service.
              We do not endorse or assume any responsibility for the conduct, performance, or omissions of any
              third-party delivery provider. Any dispute regarding a delivery (e.g., loss, damage, delay, injury)
              is between you and the third-party provider.
            </p>
          )
        },
        {
          title: '5. Limitation of Liability – Third-Party Delivery',
          content: (
            <>
              <p>
                To the maximum extent permitted by law, Tavari and its affiliates, officers, directors, employees,
                and agents shall not be liable for any loss, damage, delay, injury, or claim arising from or related
                to the acts, errors, or omissions of any third-party delivery provider, including but not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Loss, damage, or theft of goods in transit</li>
                <li>Delays, missed deliveries, or failure to perform</li>
                <li>Personal injury or property damage caused by the third-party provider or its personnel</li>
                <li>Violations of law or regulation by the third-party provider</li>
                <li>Any conduct or service quality of the third-party provider</li>
              </ul>
              <p className="mt-4">
                <strong>Liability for the delivery service rests solely with the third-party provider that performs
                the delivery.</strong> You agree to look solely to that provider for any claims arising from the
                delivery. You release and hold harmless Tavari from any such claims to the fullest extent permitted by law.
              </p>
            </>
          )
        },
        {
          title: '6. General Limitation of Liability',
          content: (
            <p>
              Except as required by law, our total liability arising from or related to the Last-Mile Delivery
              module (including the platform, matching, or coordination services) is limited to the fees you paid
              for this module in the twelve (12) months preceding the claim. We are not liable for indirect,
              incidental, consequential, or punitive damages.
            </p>
          )
        },
        {
          title: '7. Subscription and Billing',
          content: (
            <p>
              Last-Mile Delivery operates on a subscription basis. Your subscription may include usage limits or
              fees for delivery requests. Additional terms may apply to the third-party provider's services. You may
              cancel your subscription at any time through your billing settings.
            </p>
          )
        },
        {
          title: '8. Module-Specific Terms',
          content: (
            <p>
              These terms apply specifically to the Last-Mile Delivery module. By activating this module, you agree
              to these terms in addition to Tavari AI's general Terms of Service. Your use of third-party delivery
              services may also be subject to the provider's own terms and conditions.
            </p>
          )
        }
      ]
    }
  };
  
  if (!moduleKey || !moduleTerms[moduleKey]) {
    notFound();
  }
  
  const terms = moduleTerms[moduleKey];
  
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">{terms.title}</h1>
        
        <div className="mb-6 text-sm text-gray-600 bg-white p-4 rounded-lg shadow">
          <p><strong>Module:</strong> {terms.moduleName}</p>
          <p><strong>Version:</strong> {terms.version}</p>
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
        </div>
        
        <div className="bg-white rounded-lg shadow p-8 space-y-8 text-gray-700">
          {terms.sections.map((section, index) => (
            <section key={index}>
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">{section.title}</h2>
              <div className="space-y-2">
                {section.content}
              </div>
            </section>
          ))}
        </div>
        
        <div className="mt-12 pt-8 border-t border-gray-200 bg-white p-6 rounded-lg shadow">
          <p className="text-sm text-gray-600 mb-4">
            These terms apply specifically to the {terms.moduleName} module. By using this module, 
            you also agree to Tavari AI's general <Link href="/legal/terms" className="text-blue-600 hover:underline">Terms of Service</Link>.
          </p>
          <Link 
            href={`/legal/modules/${moduleKey}/privacy`}
            className="text-sm text-blue-600 hover:underline"
          >
            Module Privacy Policy →
          </Link>
        </div>
      </div>
    </div>
  );
}

